### ISSUE TITLE
Cosmetic issue with installing via pip

### ISSUE THREAD

**Issue by sjwk** [calmh/unifi-api#23]
I've noticed that when installing the library from pypi via pip, the version numbers are messed up.  Have reproduced this on a couple of machines, both running various versions of Ubuntu.

Initially pip list (or pip freeze) showed:

    unifi(sh-.1-.git-.not.found)

Then after installing git to see if that fixed it:

    unifi (fatal-.Not.a.git.repository.-or.any.of.the.parent.directories-..git)

The library works fine, it's just a cosmetic thing with listing the version numbers.

**Comment by solarnz** [comment]
The issue is that you're evaluating the version number within setup.py. The setup.py file gets evaluated again on the client side for installation (after downloading from pypi), which won't have a git repository.

**Comment by flyte** [comment]
Might I suggest using [bumpversion](https://github.com/peritus/bumpversion) to handle versioning? Instead of tagging manually you can run, for example, "bumpversion patch" which can update the version number in setup.py (instead of trying to figure it out dynamically, causing this issue), commit, and tag the version number.

If you're not 100% against the idea, let me know and I'll set it up for you.

Here's an example of its configuration in one of my projects:
[setup.py](https://github.com/0x07Ltd/django-generic-counter/blob/develop/setup.py)
[setup.cfg](https://github.com/0x07Ltd/django-generic-counter/blob/develop/setup.cfg)
